server:
  port: 8080

spring:
  application:
    name: api-gateway

  eureka:
    client:
      service-url:
       defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  cloud:
    gateway:
     routes:
      - id: Pixel-Palace-MsMangement
        predicates:
          - Path=/user/**
        uri: http://localhost:8081
      - id: Pixel-Palace-MsMarketTransactions
        predicates:
          - Path=/api/v1/**
        uri: http://localhost:8082
